server:
  port: 8081

keycloak:
  client-id: 
  client-secret:
  token-uri: http://localhost:9000/realms/my-realm/protocol/openid-connect/token

resource-server:
  url: http://localhost:8082/protected/